### PR TITLE
fix: Syntax in `compat/client` for IE11 support

### LINKED ISSUE #4371: `createRoot` uses an unsupported syntax for IE11
- [ X ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
The `createRoot` uses the "method definition" syntax which is [not supported in IE11](https://caniuse.com/mdn-javascript_functions_method_definitions):
https://github.com/preactjs/preact/blob/d18ac9f697e3604495d6496e4973c0af555ae7ba/compat/client.js#L3-L12

### PR DESCRIPTION
**Pull request by rschristian**
Closes #4371

Not that this case is problematic, but might be worth considering passing all package exports through Microbundle in the future to catch this sort of thing.

### CODE REVIEW

File: compat/client.js [hunk 1]
```diff
@@ -2,10 +2,10 @@ const { render, hydrate, unmountComponentAtNode } = require('preact/compat');
 
 function createRoot(container) {
 	return {
-		render(children) {
+		render: function (children) {
```
Comment (rschristian) [inline compat/client.js:5]:
```suggestion
		// eslint-disable-next-line
		render: function (children) {
```

File: compat/client.mjs [hunk 2]
```diff
@@ -2,10 +2,10 @@ import { render, hydrate, unmountComponentAtNode } from 'preact/compat';
 
 export function createRoot(container) {
 	return {
-		render(children) {
+		render: function (children) {
```
Comment (rschristian) [inline compat/client.mjs:5]:
```suggestion
		// eslint-disable-next-line
		render: function (children) {
```

File: compat/client.js [hunk 3]
```diff
@@ -2,10 +2,10 @@ const { render, hydrate, unmountComponentAtNode } = require('preact/compat');
...
 			render(children, container);
 		},
-		unmount() {
+		unmount: function () {
```
Comment (rschristian) [inline compat/client.js:8]:
```suggestion
		// eslint-disable-next-line
		unmount: function () {
```

File: compat/client.mjs [hunk 4]
```diff
@@ -2,10 +2,10 @@ import { render, hydrate, unmountComponentAtNode } from 'preact/compat';
...
 			render(children, container);
 		},
-		unmount() {
+		unmount: function () {
```
Comment (rschristian) [inline compat/client.mjs:8]:
```suggestion
		// eslint-disable-next-line
		unmount: function () {
```

**Review by marvinhagemeister — APPROVED** [review]
