### PR TITLE
Fix memory leak

### LINKED ISSUE #4679: Fragments cause memory leak
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Wrapping component expressions in a Fragment causes a memory leak. https://github.com/preactjs/preact/issues/3668 also concerns a possible memory leak, but it may be unrelated.

**To Reproduce**

```js
<!-- no memory leak -->>
<div>{state}</div>

<>
  <!-- memory leak -->
  <div>{state}</div>
</>
```

I reproduced the issue [here](https://github.com/builds-dev/preact-memory-leak-repro) by initializing the vite preact starter template and wrapping the top level component in `<></>`. To make the memory leak obvious, I added some fluff (a bunch of divs) so that the memory piles up quickly, but it should very slowly leak memory without it. I originally discovered this issue in Electron 22 and Electron 32 (Chrome), and then tested my reproduction repo on Firefox and Chromium (on Ubuntu 22), and observed the memory leak.

I tested Preact v10.6.0, the current v10.26.0 and the upcoming v11. The memory leak occurs in all versions.

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fixes #4679 

Basically what happens is that when we encounter a fragment we unwrap it to return is children, this way when elements get wrapped with fragments we don't risk losing state. This has a consequence when it is used in hooks environments.

As can be seen in the reproduction, if an effect closure takes a snapshot of the outer closure it will take the `Fragment` we unwrap into memory, this means that we'll effectively start mutating its children.

Every time we rerender we'll take a new snapshot of the closure which retains a copy of `Fragment` with pointers to all of its populated children.

With this measure we counter-act this by removing the reference to `children` which removes the risk of tracking this.

Fun fact, when we implement #4679's replay with class components there is no memory leak.

### CODE REVIEW

File: src/diff/index.js [hunk 1]
```diff
@@ -259,6 +259,11 @@ export function diff(
 				tmp != null && tmp.type === Fragment && tmp.key == null;
 			let renderResult = isTopLevelFragment ? tmp.props.children : tmp;
 
+			if (isTopLevelFragment) {
+				tmp.props.children = null;
+				console.log('isTopLevelFragment', tmp);
```
Comment (JoviDeCroock) [inline src/diff/index.js:264]:
```suggestion
```

**Review by marvinhagemeister — APPROVED** [review]
LGTM, really good work on debugging and finding this!!

**Review by rschristian — APPROVED** [review]
Awesome find!

**Review by developit — APPROVED** [review]

**Comment by vpzomtrrfrt** [comment]
This appears to have broken rendering for me in some cases

haven't narrowed down exactly when yet

**Comment by JoviDeCroock** [comment]
The only possibility that I see for this to fail would be something like `const x = (<>Foo</>)` and reusing that across your app
