### PR TITLE
Fix UNSAFE_* lifecycles being overwritten

### LINKED ISSUE #1941: Preact@10.0.0-rc.3 preact/compat not calling UNSAFE* functions
I'm working with react-table in the latest version 6.10.3 they have renamed the deprecated methods by adding the UNKOWN prefix (https://github.com/tannerlinsley/react-table/pull/1461). However when working with Peact X and preact/compat these functions are not being called. 

Should preact/compat patch the unsafe functions on Component? 
This https://github.com/preactjs/preact/blob/master/compat/src/index.js#L368 seems to patch the functions on the Component.

In this issue https://github.com/preactjs/preact/issues/1461 you mention keeping them until they are removed from react. Does Preact X with preact/compat support the UNSAFE* functions ?

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This was caused by transpilers overwriting our patched property when inheritance was in play. It's based on the assumption that having both the prefixed `UNSAFE_*` and the unprefixed lifecycle hook is invalid.

Fixes #1941
Adds `+29 B` to compat.

### CODE REVIEW

File: compat/src/index.js [hunk 1]
```diff
@@ -406,6 +404,16 @@ options.vnode = vnode => {
 		vnode.props.ref = vnode.ref;
 		vnode.ref = null;
 	}
+
+	// We can't just patch the base component class, because components that use
+	// inheritance and are transpiled down to ES5 will overwrite our patched
+	// getters and setters. See #1941
+	if (typeof type === 'function' && !type._patchedLifecycles && type.prototype) {
+		setSafeDescriptor(type, 'componentWillMount');
```
Comment (developit) [inline compat/src/index.js]: A thought: passing `type.prototype` here could save a couple bytes and property lookups.

**Comment by JoviDeCroock** [comment]
Are we okay with merging this and doing the optimisation as a patch release?

File: compat/src/index.js (hunk 1 above)
Comment (marvinhagemeister) [reply compat/src/index.js]: Tried it out, but it looks like gzip already plays in our favor. Using a variable to store the `prototype` will lead to the same size and passing it directly is indeed `1B` smaller :tada:
