### PR TITLE
Suspended components should rerender through sCU

### LINKED ISSUE #2176: Issue with Suspense + Lazy + @reach/router
Reach Router(https://github.com/reach/router) has an issue where it doesn't seem to trigger re-render once the Suspended Component is ready. In my projects if I navigate away and then come back again or do something to cause the parent to re-render suddenly the content is there. But otherwise it never shows on its own. 

There appears to be no errors in the console. The content just does not appear as expected if Suspense is triggered on render.

I forked the sandbox for a React Router issue(which seems now to be fixed in 10.1.0). This example uses @react/router instead and appears to still be broken:
https://codesandbox.io/s/preact-suspense-lazy-issue-tdfjc

### PR DESCRIPTION
**Pull request by andrewiggins**
Resurrecting the awesome work @sventschui did in #1660 now built on top of @jviide and @prateekbh suspense changes. Just calls `forceUpdate` on the suspended component to guarantee it rerenders when the promise resolves.

Fixes #2176

### CODE REVIEW

File: debug/src/debug.js [hunk 1]
```diff
@@ -376,7 +376,7 @@ Component.prototype.forceUpdate = function(callback) {
 		);
 	} else if (this._parentDom == null) {
 		console.warn(
-			`Can't call "this.setState" on an unmounted component. This is a no-op, ` +
+			`Can't call "this.forceUpdate" on an unmounted component. This is a no-op, ` +
```
Comment (marvinhagemeister) [inline debug/src/debug.js]: Wondering if we should mention both here. The user is probably not aware that we call `forceUpdate` for `setState` under the hood.

File: compat/src/suspense.js [hunk 2]
```diff
@@ -60,6 +61,7 @@ Suspense.prototype._childDidSuspend = function(promise) {
 		if (!--c._suspensions) {
 			c._vnode._children[0] = c.state._suspended;
 			c.setState({ _suspended: (c._detachOnNextRender = null) });
+			suspender.forceUpdate();
```
Comment (sventschui) [inline compat/src/suspense.js]: Don't we need to forceUpdate all the children that once suspended here? I.e. if `!--c._suspensions` is false that child needs to be force updated once `!--c._suspensions` goes to through in a later resolved suspension. Or am I missing a point here?

Comment (andrewiggins) [reply compat/src/suspense.js]: Oh true! Lemme extend my tests and try again

File: debug/src/debug.js (hunk 1 above)
Comment (andrewiggins) [reply debug/src/debug.js]: I think since #1939 forceUpdate and setState and fully independent if I'm reading this correctly.

File: compat/src/suspense.js (hunk 2 above)
Comment (andrewiggins) [reply compat/src/suspense.js]: Added tests. Need to think more on this...

**Comment by sventschui** [comment]
Your current approach is currently running into similar issues as #2159 

This makes me rethink our decision to unmount suspended content instead of adding `display="none"` as react does. But from the early days I remember adding a `display="none"` is not that easy

File: compat/src/suspense.js [hunk 3]
```diff
@@ -73,13 +79,18 @@ Suspense.prototype._childDidSuspend = function(promise, suspendingComponent) {
 	};
 
 	const onSuspensionComplete = () => {
-		if (!--c._suspensions) {
+		if (!--c._pendingSuspensionCount) {
 			c._vnode._children[0] = c.state._suspended;
 			c.setState({ _suspended: (c._detachOnNextRender = null) });
+
+			let suspended;
```
Comment (andrewiggins) [inline compat/src/suspense.js]: I didn't spend much time golfing this so there might be a smaller alternative

File: compat/src/suspense.js [hunk 4]
```diff
@@ -73,13 +79,18 @@ Suspense.prototype._childDidSuspend = function(promise, suspendingComponent) {
...
+			while ((suspended = c._suspenders.pop())) {
+				suspended.forceUpdate();
```
Comment (andrewiggins) [inline compat/src/suspense.js]: Note: I think this is a no-op if no sCU component is between Suspense and Lazy cuz `process()` will sort the render such that Suspense and all its children are diffed first, then when the Lazy forceUpdate are handled, the component will no longer be marked "_dirty" so they will be skipped

File: compat/test/browser/suspense.test.js [hunk 5]
```diff
@@ -55,7 +56,7 @@ export function createSuspender(DefaultComponent) {
 		}
 
 		render(props, state) {
-			return state.Lazy ? h(state.Lazy, {}) : h(DefaultComponent, {});
+			return state.Lazy ? h(state.Lazy, props) : h(DefaultComponent, props);
```
Comment (sventschui) [inline compat/test/browser/suspense.test.js]: Are props really meant to be passed down?

Comment (andrewiggins) [reply compat/test/browser/suspense.test.js]: That was my intention. Mimics what React.lazy allows: https://codesandbox.io/s/reactlazy-prop-passing-b8txb
