### PR TITLE
types: Add `indeterminate` property

### LINKED ISSUE #3836: Typescript:  input property indeterminate is not typed
**Describe the bug**
When using Preact with typescript, the `indeterminate` property on checkboxes cannot be set.  This is a type-only issue, as the property works correctly in the browser.

**To Reproduce**
Typescript playground:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAIjFApgQwMYwQbgLABQokscASulnAGZQQiLKUwD0G9YarAzlBroUIsWcAGJpgAG25wYEWQE8wKDAAsVAazgQAdnAAKqTPABSAZQAahADzAdYAK7wYSlAF4EazQCMIADwQ4OwATFBgUKBA7LhQ4FgA+QQJhOAAVVy8MDRlkCGUoSQVtPRh1OFQAcwdJNCg4ABEAeQBZIJ1wqGpMFG5CUIwa1DgAN1q2xxgAUUkALjgACVTmgBkASXsnaZQQFHb8Ig2pyQA6ELCIqJ0Y-aA

**Expected behavior**
The above code should be accepted by the typechecker.

### PR DESCRIPTION
**Pull request by rschristian**
Close #3836

Not entirely sure this is correct though; this cannot be set via HTML attributes and it doesn't appear that React supports it in JSX either. Not sure what the going practice is for these sorts of situations, but thought I'd open this anyways.

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]

**Review by JoviDeCroock — APPROVED** [review]

File: src/jsx.d.ts [hunk 1]
```diff
@@ -1425,11 +1426,11 @@ export namespace JSXInternal {
 		high?: number | undefined | SignalLike<number | undefined>;
 		href?: string | undefined | SignalLike<string | undefined>;
 		hrefLang?: string | undefined | SignalLike<string | undefined>;
-		for?: string | undefined | SignalLike<string | undefined>;
```
Comment (rschristian) [inline src/jsx.d.ts:1428]: Irrelevant to the PR of course, just caught my eye being out of place.
