### PR TITLE
fix (un)mounting of refs

### LINKED ISSUE #3404: Issue 3397 is not fully fixed: childInternal is not updated when ref transitions from non-null to null
Applies to: main branch (11.x) 

To reproduce, use test case included with issue 3397
1) Press 'Render with ref'. <span>Hello World with ref!</span> gets logged as expected
2) Press 'Render with no ref'. Nothing gets logged as expected
3) Press 'Render with ref'. Two messages logged: 'null' and '<span>Hello World with ref!</span>'

In (3), the expected behavior is that only one message should be logged (<span>Hello World with ref!</span>)

I think the issue is that childInternal.ref only gets updated when childVNode.ref is non-null. We should be updating it every time IMO, i.e. the assignment should happen before the 'if' block:

			childInternal.ref = childVNode.ref;
			if (childVNode.ref) {
				if (!refs) refs = [];
				// childInternal.ref = childVNode.ref;
				refs.push(
					oldVNodeRef,
					childVNode.ref,
					childInternal.flags & TYPE_COMPONENT
						? childInternal._component || newDom
						: newDom,
					childInternal
				);
			}

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fixes #3404 

https://codesandbox.io/s/hopeful-leaf-mci3t?file=/src/App.js

### CODE REVIEW

**Review by developit — APPROVED** [review]

File: src/diff/children.js [hunk 1]
```diff
@@ -113,9 +113,9 @@ export function diffChildren(
 
 		newDom = childInternal._dom;
 
-		if (childVNode.ref) {
+		if (childVNode.ref || oldVNodeRef) {
```
Comment (developit) [inline src/diff/children.js:116]: Wondering if we even need the conditional here, or could just always assign.

**Review by developit — APPROVED** [review]

File: src/diff/children.js (hunk 1 above)
Comment (JoviDeCroock) [reply src/diff/children.js:116]: To me this felt like a performance bottleneck as we keep on piling into the array then for every element, now it's only for elements that once had a ref in the current or prev cycle
