### PR TITLE
Sort new renderqueue items

### LINKED ISSUE #2393: createContext is not fully React compatible
After migrating an app from React to Preact 10, we noticed that some of our components were unmounting with the incorrect props.

### Reproduction

Here is a reproduction of the issue on simplified codebase.

Preact: https://codesandbox.io/s/upbeat-pasteur-r7soh
React: https://codesandbox.io/s/wonderful-worker-u3uus

### Steps to reproduce

So, the idea is that because of the `key` prop assigned to `Parent`, when `id` changes, it should unmount it with the previous id and then mount it with the new one. That's my expectation at least and it works like that in React. Here is the console output when clicking on the text.

```
// React
render, id 0
mount, id 0
render, id 1
unmount, id 0
mount, id 1
```

But for Preact, I'm not fully sure, but it seems that nested consumers will update first, meaning that `Child` will be updated with the new id and only then will `Parent` realize that its `key` has changed and will unmount. Here are the console logs for the same click:

```
// Preact
render, id 0
mount, id 0
render, id 1
updated from 0 to 1
render, id 1
unmount, id 1
mount, id 1
```

As we can see, there is an `update` lifecycle now and the unmount is done with `props.id` at `1` rather than `0`.

I wonder if either React is maintaining a more optimized stack for consumers or, even better, batch all updates to all consumers in one render.

### Expected Behavior

`Child` component should not update and unmount directly with `id: 0`.

### Actual Behavior

`Child` component is updated to `id: 1` and unmounted with that value.

### PR DESCRIPTION
**Pull request by jviide**
This pull request attempts to fix #2393 by modifying how the global `renderQueue` is processed. 

Currently `renderQueue` is sorted by vnode depth before its items are processed, but if new items get queued during processing (and `renderQueue.length > 1`) then those new items are also processed _without_ them getting sorted by depth first.

This pull attempts fixing that. When `renderQueue` is processed, it's item count is checked. If there are no items then we can stop. Otherwise the queue is sorted by depth and stored into a temporary variable while `renderQueue` itself is reinitialized with a new, _empty_ array. Now the "old" queued items get processed and any new items get added to the new `renderQueue` list.

After the all old items have been processed the new `renderQueue` is checked & sorted again, and the cycle starts anew.

A great test from @JoviDeCroock's alternative PR #2395 is also included here.

Fixes #2393

### CODE REVIEW

File: src/component.js [hunk 1]
```diff
@@ -190,7 +191,10 @@ let prevDebounce;
  */
 export function enqueueRender(c) {
 	if (
-		(!c._dirty && (c._dirty = true) && rerenderQueue.push(c) === 1) ||
+		(!c._dirty &&
+			(c._dirty = true) &&
+			rerenderQueue.push(c) &&
+			!rerenderCount++) ||
```
Comment (marvinhagemeister) [inline src/component.js]: We might be lacking a test case for this change. All tests keep passing when I remove the `rerenderCount` check.

Comment (jviide) [reply src/component.js]: Good point. I added a test to browser/render.test.js that passes with this PR, but fails on master or if you remove the `rerenderCount` check.
